### PR TITLE
Fix serial ID tracking

### LINKED ISSUE #33: Clipboard updates only once
This was reported to Alacritty in https://github.com/alacritty/alacritty/issues/4735.

It seems like the clipboard has an issue where it only updates its content once on some compositors (GNOME/weston) and requires users to switch applications before they can write to the clipboard again.

@r-c-f has provided a very helpful Wayland log, which suggests the problem might be with smithay-clipboard not cancelling the data source for the clipboard data: https://github.com/alacritty/alacritty/issues/4735#issuecomment-769735431

According to @jamesodhunt this regression was introduced in https://github.com/Smithay/smithay-clipboard/commit/f6f5b98235b1a5052aff1fb5a48e7951720beb42: https://github.com/alacritty/alacritty/issues/4735#issuecomment-769737024

### PR DESCRIPTION
**Pull request by chrisduerr**
The serial ID tracking was incorrectly reinserting any previously used
seats without updating the serial information, leading to consecutive
clipboard stores being dropped by the compositor.

Fixes #33.

### CODE REVIEW

File: src/worker/dispatch_data.rs [hunk 1]
```diff
@@ -37,28 +37,18 @@ impl ClipboardDispatchData {
...
     /// Set the last observed seat.
     pub fn set_last_observed_seat(&mut self, seat: WlSeat, serial: u32) {
-        let pos = self.observed_seats.iter().position(|st| st.0 == seat);
-        let (seat, serial) = match pos {
-            Some(pos) => {
-                // We just found that `pos` we're going to remove, so unwrapping is safe.
-                self.observed_seats.remove(pos).unwrap()
-            }
-            None => (seat, serial),
-        };
```
Comment (chrisduerr) [inline src/worker/dispatch_data.rs:47]: This should be the problematic code. Getting the `serial` here from the removed element rather than using the serial passed into the function leads to a reuse of the old serial updating absolutely nothing.

**Comment by elinorbgr** [comment]
Looks good to me, have you tested it?

**Comment by chrisduerr** [comment]
> Looks good to me, have you tested it?

I have, it does seem to work.

**Comment by elinorbgr** [comment]
Alright, thanks!
