### PR TITLE
Fix panic when wayland display connection breaks

### LINKED ISSUE #1: enter_serial should come from the library user
You can't get an `enter_serial` if you just have a `wl_display`.

### LINKED ISSUE #52: Crash when running in WSL2
I am running a demo code of slint on WSL2, smithay-clipboard is crashed. [`Slint`](https://github.com/slint-ui/slint/issues/4089#issue-2028408823)

Platform: `WSL2` `Fedora release 39 (Thirty Nine)` 
Slint: 1.3.2
```
Io error: Broken pipe (os error 32)
thread 'Io error: smithay-clipboard' panicked at /home/xxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smithay-clipboard-0.7.0/src/worker.rs:98Broken pipe: (os error 4732:
)called `Result::unwrap()` on an `Err` value: OtherError(IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }))

stack backtrace:
Io error: Broken pipe (os error 32)
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1077:23
   4: smithay_clipboard::worker::worker_impl
             at /home/xxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smithay-clipboard-0.7.0/src/worker.rs:98:9
   5: smithay_clipboard::worker::spawn::{{closure}}
             at /home/xxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smithay-clipboard-0.7.0/src/worker.rs:23:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: Other("Error running winit event loop: Exit Failure: 1")

 *  The terminal process "cargo 'run', '--package', 'slint-demo', '--bin', 'slint-demo'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.
```

```
fn main() -> Result<(), Box<dyn std::error::Error>> {
    MainWindow::new()?.run()?;
    Ok(())
}

slint::slint! {
    export component MainWindow inherits Window {
        Text {
            text: "Hello World!";
            color: red;
        }
    }
}
```
Running with `cargo run`, with default feature.

### PR DESCRIPTION
**Pull request by tronical**
Instead, terminate the thread and consider the clipboard dead. The application can now gracefully deal with the situation.

Closes #52

### CODE REVIEW

File: src/worker.rs [hunk 1]
```diff
@@ -95,7 +95,11 @@ fn worker_impl(
...
     loop {
-        event_loop.dispatch(None, &mut state).unwrap();
+        if event_loop.dispatch(None, &mut state).is_err() {
+            // Possibly broken connection to the display server, not much we can
+            // do at this point.
+            break;
+        }
 
         if state.exit {
             break;
```
Comment (kchibisov) [inline src/worker.rs]: Should just merge both `if`.

**Review by kchibisov — APPROVED** [review]

**Comment by kchibisov** [comment]
Could you fixup CI while at it, I don't want to push to your master branch myself.

**Comment by tronical** [comment]
Sure :)
